export const searchActionId = "search_action";
export const searchButtonActionId = "search_button_action";
export const searchModalId = "search_modal";
export const searchDispatchActionId = "search_dispatch_action";
export const searchConfluenceCheckedActionId = "search_confluence_checked_action";
export const searchConfluneceCheckBlockId = "search_confluence_checkbox_block";
export const confluenceSiteUrlDisplayBlockId = "confluence_site_url_display_block";
export const searchConfluenceLogoutActionId = "confluence_search_logout_action";
export const searchInputBlockId = "search_input_block";
export const searchConfluenceTimeout = 2 * 1000; // 2 secs